### ISSUE TITLE
'nbstripout' is not recognized as an internal or external command, operable program or batch file. 

### ISSUE THREAD

**Issue by hlwestberg** [kynan/nbstripout#183]
```

'nbstripout' is not recognized as an internal or external command,
operable program or batch file.
```

Trying to install nbstripout on windows. pip install works fine, but nbstripout --install does not. I keep getting the error above. 
Python and git are in my PATH variable, and I can run git commands from the command line inside the repo. 
When I run pip list, I see nbstripout listed, so I know it's downloaded.

**Comment by kynan** [comment]
When you `pip install nbstripout`, `nbstripout` is installed as an entrypoint script. I have no idea where those live on Windows and whether that directory is on your `PATH`. I assume not, which is why you see the error.

You can either add that directory to your `PATH` or simply run `python -m nbstripout` instead of `nbstripout`.

**Comment by hlwestberg** [comment]
Got it, thanks!
