### ISSUE TITLE
Add stripping for associated .py files

### ISSUE THREAD

**Issue by krfighter** [kynan/nbstripout#35]
Could you please add a feature for stripping associated py files?
In py files there are lines
`# In[XXX]:`
which should be stripped back to 
`# In[ ]:`

It would be immensely helpful to have this feature!

Thanks,
Andrew

**Comment by kynan** [comment]
You can achieve that with a simple `sed` command:

    sed 's/In\[[0-9]\+\]:/In[ ]:/' yourfile.py

I don't think this is something `nbstripout` should handle. What is your use case / workflow?

**Comment by krfighter** [comment]
either sed or a small python script would work. I use GIT on Windows and I have automatic saving of python copies of my notebooks setup in jupyter. I can certainly add this feature separately on my system, but I am sure there are quite a few people who use this feature of jupyter, and they would also need it.
What do you think?

**Comment by kynan** [comment]
I'm still not convinced `nbstripout` is the tool to handle this. It's really geared towards notebooks and having it handle Python scripts raises a number of questions:
* Presumably you don't want to apply this filter to all Python scripts but only those exported from notebooks. So setting up the filter by file extension won't cut it.
* `nbstripout` can (and does, when used as a Git filter) read from stdin and therefore doesn't even know the file extension.
* Even if it did, that would not be safe, so it would need to detect the file type or be told via a flag.

I'd rather keep `nbstripout` focussed on notebooks and handle that case well than adding a feature to handle an edge case that will confuse the majority of users.

Why don't you set up that `sed` command as a filter for your Python scripts? Arguably you might not even want to track those in Git since they're automatically generated.
