### ISSUE TITLE
Fix Windows tests

### ISSUE THREAD

**Issue by kynan** [kynan/nbstripout#38]
Tests are currently failing on Windows due to cram not unifying line endings, see brodie/cram#9.

**Comment by zertrin** [comment]
I've tried to use cram myself for a project and got bitten by this.

This commit https://github.com/zertrin/nbstripout/commit/920bb050220666818c8feb4bacbd57815fbc1dbe tries to minimize the problem but doesn't solve it... Lines with options like `(re)` can't be fixed by the core.autocrlf trick.

My conclusion at this point is that cram is not usable on windows. I have dropped it from my project since a look at their issue tracker and git activity shows that the project is not gonna fix this anytime soon.

**Comment by kynan** [comment]
@zertrin thanks for looking into this. Great idea using `core.autocrlf`, I'll apply that change anyway, even though it doesn't fix it.

The only solution at this point is probably forking cram until @brodie picks up the project again.

**Comment by arobrien** [comment]
https://github.com/brodie/cram hasn't had a release since 2016 and is now archived. It's probably easier to port the tests to another framework than to fix/update/fork/whatever cram.

**Comment by kynan** [comment]
Yes, that's what I'm intending to do. See #165.

**Comment by kynan** [comment]
@arobrien interested to help with this?
