### ISSUE TITLE
Creating a branch with notebook outputs stripped

### ISSUE THREAD

**Issue by psychemedia** [kynan/nbstripout#71]
Is there a way of using `nbstripout` that would allow me to create a branch of cleaned notebooks from a branch that contains notebooks with populated output cells (eg ones with output cells populated that can be used for testing with [`nbval`](https://github.com/computationalmodelling/nbval)).

I'm thinking of a private github repo workflow where there is a *testing-master* branch containing executed notebooks with populated test output cells that begets a *release* branch containing notebooks that can be zipped and distributed to students.

Presumably, a variant of `nbstripout` could also be used to add a git filter that would automatically run a notebook when commiting it to a repository to ensure that all its output cells *are* populated?

**Comment by kynan** [comment]
By its nature, a git filter can only act on the commit about to be made. It's not designed to "spawn" another commit in a different branch (I suppose it could be made to do that with some trickery, but I rather wouldn't like to implement such a "hack" in nbstripout).

You can however emulate the behaviour you want by installing nbstripout only in a `.gitattributes` file in your `release` branch. Assuming your "dirty" notebooks are on master, you can create a clean branch as follows:

Create an orphan release branch and install nbstripout in that branch only:
```
git checkout --orphan release
nbstripout --install --attributes=.gitattributes
git add .gitattributes
git commit -m 'Install nbstripout'
```
You can then cherry-pick notebook commits as follows (you will probably have to do this in order to avoid merge conflicts, unless each commit is entirely self contained):
```
git cherry-pick --no-commit
git commit -a --no-edit
```
From my quick test those 2 stages are necessary for the filter to kick in i.e. if you just do a plain cherry pick the filter is not applied.

Hope this helps!

**Comment by kynan** [comment]
> Presumably, a variant of `nbstripout` could also be used to add a git filter that would automatically run a notebook when commiting it to a repository to ensure that all its output cells *are* populated?

Not easily: as mentioned, npstripout uses a [git clean/smudge filter](https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes) and operates purely on the file level. No cells are ever executed.

You would need to look at a pre-commit hook, however I expect that's not too easy to set up: you'd need to start a notebook server, run the notebook and deal with failures. This would also take very long.

If you only want to *verify* the output is populated, that's easier to do (and you could potentially reuse some of `nbstripout`'s code for that).

**Comment by kynan** [comment]
@psychemedia have you found a suitable workflow for your needs?

**Comment by psychemedia** [comment]
@kynan I've actually moved to a workflow around jupytext now that uses a text based representation for notebooks (no cell outputs).

Reflecting back, I think that a `git filter-branch --tree-filter` approach would probably work okay for a release: create new branch, run the git filter to clean all the notebooks in it, commit.
