### ISSUE TITLE
windows command

### ISSUE THREAD

**Issue by RoelantStegmann** [kynan/nbstripout#83]
git filter-branch -f --tree-filter "for /r %i in (*.ipynb) do nbstripout %i --keep-count --keep-output"

Was wondering if anyone knows the correct windows syntax by heart: i keep getting errors :) Maybe we can add it to the readme afterwards?

**Comment by kynan** [comment]
I'm not a Windows user, so can't help unfortunately. Hopefully someone from the community knows the answer, maybe @ibressler ?

**Comment by ibressler** [comment]
The command given to --tree-filter is interpreted by bash. Therefore, it works like this:
(Tested in _Anaconda Prompt_ on Win10 which is a Windows command prompt with nbstripout/Python available but not having GIT in its %PATH%)

`"c:\Program Files\Git\bin\git.exe" filter-branch -f --tree-filter "(IFS=$'\n'; for fn in $(find . -type f -name '*.ipynb'); do nbstripout \"$fn\" --keep-count --keep-output; done)"`

The most outside parentheses (aka subshell) are required to encapsulate the **IFS** setting for supporting file names with spaces. Changing the **IFS** breaks the GIT filter-branch command otherwise.

**Comment by kynan** [comment]
@RoelantStegmann Friendly ping, can this be closed?

**Comment by kynan** [comment]
Assuming this has been answered. @RoelantStegmann please reopen if not.
