### ISSUE TITLE
Handle dot in metadata key name

### ISSUE THREAD

**Issue by karlicoss** [kynan/nbstripout#95]
So I ran into a need to filter metadata key containing dot, which interferes with the way the key filter is specified in git .config file, since nbstripout uses dot as nestedness seprarator. Sadly, I don't control the key names either, they are coming from EIN Emacs plugin and seem to be [hardcoded](https://github.com/millejoh/emacs-ipython-notebook/blob/3d16ccf62af8d61a7b7d01e9d792f97a26e6ca54/lisp/ein-cell.el#L1054-L1055). 

For now I just [hacked](https://github.com/karlicoss/nbstripout/commit/53ff7368d160adc2c8901936ee3d0e4d1a8add52) nbstripout to treat dot as part of key name, but that's of course not a proper fix. Thought for a bit, but couldn't come up with a good backwards compatible solution for specifying keys containing dots, so at least leaving this issue here...

**Comment by kynan** [comment]
Sorry for the late reply. One potential option I could see is specifying metadata keys as lists instead of dot separated strings. That's a bit of effort when also trying to maintain backwards compatibility. Given that JSON keys also cannot contain dots I think lobbying for your plugin to change their metadata seems like a better solution.

Let me know what you think and if you're still facing this issue.

**Comment by kynan** [comment]
This is the same as #143, which has been addressed in #144. Please reopen if that doesn't resolve your use case.
